version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile  # Use the Dockerfile to build the image
    container_name: nestjs-app  # Name of the container
    ports:
      - "3000:3001"  # Map port 3000 on the host to port 3000 on the container
    environment:
      - NODE_ENV=production  # Set environment variable for production
    volumes:
      - .:/usr/src/app  # Mount the current directory to /usr/src/app in the container
    networks:
      - nestjs-network  # Connect this service to the custom network

# Define networks (optional but useful for multiple containers)
networks:
  nestjs-network:
    driver: bridge