version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"  # Map port 3000 on host to port 3000 in container
    env_file:
      - .env
    networks:
      - nestjs-network
    depends_on:
      - redis  # Ensure Redis is started before the NestJS app

  redis:
    image: redis:latest  # Use the official Redis image
    container_name: redis
    ports:
      - "6379:6379"  # Map port 6379 on host to port 6379 in container
    networks:
      - nestjs-network
    restart: always  # Ensure Redis restarts if it crashes

networks:
  nestjs-network:
    driver: bridge